/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicSignUpLayoutRouteImport } from './routes/_public/sign-up/layout'
import { Route as PublicSignInLayoutRouteImport } from './routes/_public/sign-in/layout'
import { Route as PublicSignUpPageRouteImport } from './routes/_public/sign-up/page'
import { Route as PublicSignInPageRouteImport } from './routes/_public/sign-in/page'
import { Route as ApiVerifyEmailTokenRouteImport } from './routes/_api/verify-email/$token'
import { Route as PrivateAppOnboardingLayoutRouteImport } from './routes/_private/_app/onboarding/layout'
import { Route as PrivateAppSidebarLayoutRouteImport } from './routes/_private/_app/_sidebar/layout'
import { Route as PrivateAppOnboardingPageRouteImport } from './routes/_private/_app/onboarding/page'

const PublicSignUpLayoutRoute = PublicSignUpLayoutRouteImport.update({
  id: '/_public/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignInLayoutRoute = PublicSignInLayoutRouteImport.update({
  id: '/_public/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignUpPageRoute = PublicSignUpPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSignUpLayoutRoute,
} as any)
const PublicSignInPageRoute = PublicSignInPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSignInLayoutRoute,
} as any)
const ApiVerifyEmailTokenRoute = ApiVerifyEmailTokenRouteImport.update({
  id: '/_api/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAppOnboardingLayoutRoute =
  PrivateAppOnboardingLayoutRouteImport.update({
    id: '/_private/_app/onboarding',
    path: '/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateAppSidebarLayoutRoute = PrivateAppSidebarLayoutRouteImport.update({
  id: '/_private/_app/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAppOnboardingPageRoute =
  PrivateAppOnboardingPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateAppOnboardingLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof PublicSignInLayoutRouteWithChildren
  '/sign-up': typeof PublicSignUpLayoutRouteWithChildren
  '/': typeof PrivateAppSidebarLayoutRoute
  '/onboarding': typeof PrivateAppOnboardingLayoutRouteWithChildren
  '/verify-email/$token': typeof ApiVerifyEmailTokenRoute
  '/sign-in/': typeof PublicSignInPageRoute
  '/sign-up/': typeof PublicSignUpPageRoute
  '/onboarding/': typeof PrivateAppOnboardingPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateAppSidebarLayoutRoute
  '/verify-email/$token': typeof ApiVerifyEmailTokenRoute
  '/sign-in': typeof PublicSignInPageRoute
  '/sign-up': typeof PublicSignUpPageRoute
  '/onboarding': typeof PrivateAppOnboardingPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public/sign-in': typeof PublicSignInLayoutRouteWithChildren
  '/_public/sign-up': typeof PublicSignUpLayoutRouteWithChildren
  '/_private/_app/_sidebar': typeof PrivateAppSidebarLayoutRoute
  '/_private/_app/onboarding': typeof PrivateAppOnboardingLayoutRouteWithChildren
  '/_api/verify-email/$token': typeof ApiVerifyEmailTokenRoute
  '/_public/sign-in/': typeof PublicSignInPageRoute
  '/_public/sign-up/': typeof PublicSignUpPageRoute
  '/_private/_app/onboarding/': typeof PrivateAppOnboardingPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/onboarding'
    | '/verify-email/$token'
    | '/sign-in/'
    | '/sign-up/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/verify-email/$token' | '/sign-in' | '/sign-up' | '/onboarding'
  id:
    | '__root__'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_private/_app/_sidebar'
    | '/_private/_app/onboarding'
    | '/_api/verify-email/$token'
    | '/_public/sign-in/'
    | '/_public/sign-up/'
    | '/_private/_app/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicSignInLayoutRoute: typeof PublicSignInLayoutRouteWithChildren
  PublicSignUpLayoutRoute: typeof PublicSignUpLayoutRouteWithChildren
  PrivateAppSidebarLayoutRoute: typeof PrivateAppSidebarLayoutRoute
  PrivateAppOnboardingLayoutRoute: typeof PrivateAppOnboardingLayoutRouteWithChildren
  ApiVerifyEmailTokenRoute: typeof ApiVerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-up/': {
      id: '/_public/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof PublicSignUpPageRouteImport
      parentRoute: typeof PublicSignUpLayoutRoute
    }
    '/_public/sign-in/': {
      id: '/_public/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof PublicSignInPageRouteImport
      parentRoute: typeof PublicSignInLayoutRoute
    }
    '/_api/verify-email/$token': {
      id: '/_api/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof ApiVerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_app/onboarding': {
      id: '/_private/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PrivateAppOnboardingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_app/_sidebar': {
      id: '/_private/_app/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateAppSidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_app/onboarding/': {
      id: '/_private/_app/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof PrivateAppOnboardingPageRouteImport
      parentRoute: typeof PrivateAppOnboardingLayoutRoute
    }
  }
}

interface PublicSignInLayoutRouteChildren {
  PublicSignInPageRoute: typeof PublicSignInPageRoute
}

const PublicSignInLayoutRouteChildren: PublicSignInLayoutRouteChildren = {
  PublicSignInPageRoute: PublicSignInPageRoute,
}

const PublicSignInLayoutRouteWithChildren =
  PublicSignInLayoutRoute._addFileChildren(PublicSignInLayoutRouteChildren)

interface PublicSignUpLayoutRouteChildren {
  PublicSignUpPageRoute: typeof PublicSignUpPageRoute
}

const PublicSignUpLayoutRouteChildren: PublicSignUpLayoutRouteChildren = {
  PublicSignUpPageRoute: PublicSignUpPageRoute,
}

const PublicSignUpLayoutRouteWithChildren =
  PublicSignUpLayoutRoute._addFileChildren(PublicSignUpLayoutRouteChildren)

interface PrivateAppOnboardingLayoutRouteChildren {
  PrivateAppOnboardingPageRoute: typeof PrivateAppOnboardingPageRoute
}

const PrivateAppOnboardingLayoutRouteChildren: PrivateAppOnboardingLayoutRouteChildren =
  {
    PrivateAppOnboardingPageRoute: PrivateAppOnboardingPageRoute,
  }

const PrivateAppOnboardingLayoutRouteWithChildren =
  PrivateAppOnboardingLayoutRoute._addFileChildren(
    PrivateAppOnboardingLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicSignInLayoutRoute: PublicSignInLayoutRouteWithChildren,
  PublicSignUpLayoutRoute: PublicSignUpLayoutRouteWithChildren,
  PrivateAppSidebarLayoutRoute: PrivateAppSidebarLayoutRoute,
  PrivateAppOnboardingLayoutRoute: PrivateAppOnboardingLayoutRouteWithChildren,
  ApiVerifyEmailTokenRoute: ApiVerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
